%YAML 1.1
---
language: d
d: [dmd, ldc]
sudo: false
addons:
  apt:
    packages:
    - libevent-dev
before_install: [pip install --user codecov, dub fetch packageversion]
script:
  - dub build --compiler=${DC}
  - dub test --compiler=${DC} --coverage
  - dub build --compiler=${DC} --build=ddox
after_success: codecov
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: "$GH_REPO_TOKEN"
  verbose: true
  keep-history: true
  true:
    branch: master
env:
  global:
    secure: CP1UBl4ReS3Z6RC9l27jI5RUgIxy8hlXORH+1Vho2DAPDuEdlDsJpSUZSrqbELBqczWQtb0rXhkWI1UqroW1apyPI3YDSxVdPp6C0FtlV9uWdpTqWwaaxsITJNvrllAJLuiQp+kNdJQAzo8YgAWStSbYl1zRyrsBfy/dOAMJtzKJUWcc2cgJGV8bTjRAH2z82urfflysEX8E2QCJ2n+8mkFjXf+RnxwD3FxtKST/zANorTZ6/BgrDRY2iYaO+shCmFZpDFo3UNElgZx/CDMWoszTz76S5FcIHJ0nvr7Uimf+C1SGnEdTYJxV7BWyIxS8S8UkG9PxHxS7tFCjMIIKr8IKehgTOc/7fB9068+0Fmd128XJ5CdioQwz52CPdJ0JJUYfQhSH00Qg4Mcltu8oIWHtbZT3A+5KJXpUFP9jNvKR236Rx1RM5Niv05jUWEj27w5dNb3p5G+Z7KiGwLDMN0/YGwAwka5f5k7UCj1Ny3BS/BEi0AOrk45mbJ+G6RLzdG3B5410KdC6MeBnST7Xxvp5RPXFfhwoOBJwlqUQiaEd+MEzMzeIfGt3RQU4AQghZpF3uwHs0opa8l+qFNW6k+J7O5ZJAaN7eb5HlRPS09jux6sT4BYez8pVIrlUgS3OSRwGevODU9O3rUS4sRaEQ/skqJUasgePPaEWzqHwYAY=
