// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'androidlogger', kind: "module", path: './androidlogger.html', attributes: []},
{name: 'androidlogger.AndroidLogger', kind: "classdeclaration", path: './androidlogger/AndroidLogger.html', attributes: []},
{name: 'androidlogger.AndroidLogger.this', kind: "functiondeclaration", path: './androidlogger/AndroidLogger.this.html', attributes: []},
{name: 'androidlogger.AndroidLogger.tid2string', kind: "functiondeclaration", path: './androidlogger/AndroidLogger.tid2string.html', attributes: ["static", "trusted"]},
{name: 'androidlogger.AndroidLogger.writeLogMsg', kind: "functiondeclaration", path: './androidlogger/AndroidLogger.writeLogMsg.html', attributes: ["override", "trusted"]},
{name: 'androidlogger.AndroidLogger.colorize', kind: "functiondeclaration", path: './androidlogger/AndroidLogger.colorize.html', attributes: ["auto"]},
{name: 'androidlogger.AndroidLogger.initLogLevel2String', kind: "functiondeclaration", path: './androidlogger/AndroidLogger.initLogLevel2String.html', attributes: []},
{name: 'androidlogger.AndroidLogger.logLevel2String', kind: "variabledeclaration", path: './androidlogger/AndroidLogger.logLevel2String.html', attributes: []},
{name: 'androidlogger.AndroidLogger.withColors', kind: "variabledeclaration", path: './androidlogger/AndroidLogger.withColors.html', attributes: []},
];
